Repository Annosz/UIInfoSuite2, pull requests merged in 2021-12, with the labels that each got.

#106 1.5.5 compatibility
  UIInfoSuite2/Properties/AssemblyInfo.cs
  UIInfoSuite2/UIInfoSuite2.csproj
  UIInfoSuite2/packages.config
Labels: breaking bug

#111 Fix saving settings
  UIInfoSuite2/ModEntry.cs
  UIInfoSuite2/Options/ModConfig.cs
Labels: bug

#116 Finished german translation
  README.md
  UIInfoSuite2/i18n/de.json
Labels: translation
