Repository Annosz/UIInfoSuite2, pull requests merged in 2021-03, with the labels that each got.

#43 Update manifest.json
  UIInfoSuite2/manifest.json
Labels: documentation

#46 Fixes heart offset #41
  UIInfoSuite2/UIElements/ShowAccurateHearts.cs
Labels: bug

#45 Add Robin building status icon
  UIInfoSuite2/Infrastucture/LanguageKeys.cs
  UIInfoSuite2/Options/ModOptionsPageHandler.cs
  UIInfoSuite2/Options/OptionKeys.cs
  UIInfoSuite2/UIElements/ShowItemEffectRanges.cs
  UIInfoSuite2/UIElements/ShowRainyDayIcon.cs
  UIInfoSuite2/UIElements/ShowRobinBuildingStatusIcon.cs
  UIInfoSuite2/UIInfoSuite2.csproj
  UIInfoSuite2/i18n/de.json
  UIInfoSuite2/i18n/default.json
  UIInfoSuite2/i18n/es.json
  UIInfoSuite2/i18n/fr.json
  UIInfoSuite2/i18n/hu.json
  UIInfoSuite2/i18n/ja.json
  UIInfoSuite2/i18n/ko.json
  UIInfoSuite2/i18n/pt.json
  UIInfoSuite2/i18n/ru.json
  UIInfoSuite2/i18n/th.json
  UIInfoSuite2/i18n/zh.json
Labels: enhancement

#49 Show if gift has been given today
  UIInfoSuite2/Options/ModOptionsPageHandler.cs
  UIInfoSuite2/Options/OptionKeys.cs
  UIInfoSuite2/UIElements/ShowAccurateHearts.cs
  UIInfoSuite2/UIElements/ShowTodaysGifts.cs
  UIInfoSuite2/UIInfoSuite2.csproj
  UIInfoSuite2/i18n/default.json
Labels: enhancement
