Repository Annosz/UIInfoSuite2, pull requests merged in 2022-11, with the labels that each got.

#243 Only show the item tooltip in the inventory page
  UIInfoSuite2/Infrastructure/Tools.cs
Labels: bug

#259 Handle multiple birthdays on the same day
  UIInfoSuite2/UIElements/ShowBirthdayIcon.cs
Labels: enhancement

#258 Show a frying pan instead of the trash can
  UIInfoSuite2/UIElements/ShowToolUpgradeStatus.cs
Labels: mod compatibility

#257 Fix crash when resizing mod options page and display its tab correctly
  UIInfoSuite2/Options/ModOptionsPageHandler.cs
Labels: bug

#242 Show growth time for potted tea saplings
  UIInfoSuite2/UIElements/ShowCropAndBarrelTime.cs
Labels: bug

#262 Use tea bush constant for comparison
  UIInfoSuite2/UIElements/ShowCropAndBarrelTime.cs
Labels: code cleanup

#261 Changing a secondary setting also toggles recalculation
  UIInfoSuite2/Options/ModOptionsPageHandler.cs
  UIInfoSuite2/UIElements/LuckOfDay.cs
  UIInfoSuite2/UIElements/ShowBirthdayIcon.cs
  UIInfoSuite2/UIElements/ShowSeasonalBerry.cs
  UIInfoSuite2/UIElements/ShowTravelingMerchant.cs
  UIInfoSuite2/UIElements/ShowWhenAnimalNeedsPet.cs
Labels: bug

#238 Show harvest prices for modded crops
  UIInfoSuite2/Infrastructure/Tools.cs
  UIInfoSuite2/UIElements/ShopHarvestPrices.cs
  UIInfoSuite2/UIElements/ShowItemHoverInformation.cs
Labels: mod compatibility
