Repository Annosz/UIInfoSuite2, pull requests merged in 2022-07, with the labels that each got.

#199 Fix Queen Of Sauce icon not disappearing
  UIInfoSuite2/UIElements/ShowQueenOfSauceIcon.cs
Labels: bug

#207 Warn if Generic Mod Config Menu is older than 1.6.0
  UIInfoSuite2/ModEntry.cs
Labels: bug

#193 Add TODO strings & Correct hazelnut icon date
  README.md
  UIInfoSuite2/UIElements/ShowSeasonalBerry.cs
  UIInfoSuite2/i18n/de.json
  UIInfoSuite2/i18n/es.json
  UIInfoSuite2/i18n/fr.json
  UIInfoSuite2/i18n/hu.json
  UIInfoSuite2/i18n/ja.json
  UIInfoSuite2/i18n/ko.json
  UIInfoSuite2/i18n/pl.json
  UIInfoSuite2/i18n/pt.json
  UIInfoSuite2/i18n/ru.json
  UIInfoSuite2/i18n/tr.json
  UIInfoSuite2/i18n/uk.json
  UIInfoSuite2/i18n/zh.json
Labels: bug, translation

#173 Update zh.json
  UIInfoSuite2/i18n/zh.json
Labels: translation

#191 Update th.json
  UIInfoSuite2/i18n/th.json
Labels: translation

#198 Update Ukrainian translation for UIInfoSuite2
  UIInfoSuite2/i18n/uk.json
Labels: translation

#201 Show the needs pet indicator on pets indoors
  UIInfoSuite2/UIElements/ShowWhenAnimalNeedsPet.cs
Labels: bug

#210 Update tr.json
  UIInfoSuite2/i18n/tr.json
Labels: translation

#212 [Translation] Translated all todos in pt.json
  UIInfoSuite2/i18n/pt.json
Labels: translation

#213 Update ru.json
  UIInfoSuite2/i18n/ru.json
Labels: translation

#216 Update ja.json
  UIInfoSuite2/i18n/ja.json
Labels: translation

#200 Label wild seeds correctly
  UIInfoSuite2/UIElements/ShowCropAndBarrelTime.cs
Labels: bug

#206 Fix wrongly labeling items for bundles
  UIInfoSuite2/UIElements/ShowItemHoverInformation.cs
Labels: bug

#218 Fix my own bug which broke bundle labels
  UIInfoSuite2/UIElements/ShowItemHoverInformation.cs
Labels: bug

#214 Fix tab icon display
  UIInfoSuite2/Options/ModOptionsPageHandler.cs
Labels: enhancement

#223 Update tr.json
  UIInfoSuite2/i18n/tr.json
Labels: translation
