Repository Annosz/UIInfoSuite2, pull requests merged in 2022-04, with the labels that each got.

#146 Add Suggestions
  UIInfoSuite2/Options/ModOptions.cs
  UIInfoSuite2/Options/ModOptionsPageHandler.cs
  UIInfoSuite2/UIElements/ShowBirthdayIcon.cs
  UIInfoSuite2/i18n/default.json
Labels: enhancement

#151 Fix issues with B and H keybinds
  UIInfoSuite2/Compatibility/IGenericModConfigMenuApi.cs
  UIInfoSuite2/Compatibility/ILevelExtender.cs
  UIInfoSuite2/ModEntry.cs
  UIInfoSuite2/Options/ModConfig.cs
  UIInfoSuite2/Options/ModOptions.cs
  UIInfoSuite2/UIElements/ExperienceBar.cs
Labels: bug, enhancement, mod compatibility

#154 Solve conflict with BFAV
  UIInfoSuite2/UIElements/ShowWhenAnimalNeedsPet.cs
Labels: bug, mod compatibility

#157 Fix translation on bundle name tooltip
  UIInfoSuite2/Options/ModOptionsPageHandler.cs
  UIInfoSuite2/UIElements/ShowItemHoverInformation.cs
Labels: bug

#155 Show cooking recipies with localized name
  UIInfoSuite2/UIElements/ShowQueenOfSauceIcon.cs
Labels: bug
