Repository Annosz/UIInfoSuite2, pull requests merged in 2022-03, with the labels that each got.

#107 Improve sprinkler tile highlighting
  UIInfoSuite2/UIElements/ShowItemEffectRanges.cs
Labels: bug

#150 Calendar and billboard button deregistration
  UIInfoSuite2/ModEntry.cs
  UIInfoSuite2/UIElements/ShowCalendarAndBillboardOnGameMenuButton.cs
Labels: enhancement

#114 Update translations & docs
  README.md
  UIInfoSuite2/i18n/pl.json
  UIInfoSuite2/i18n/uk.json
Labels: translation

#131 Update ru.json
  UIInfoSuite2/i18n/ru.json
Labels: translation

#134 Update Ukrainian translation for UIInfoSuite2
  UIInfoSuite2/i18n/uk.json
Labels: translation

#147 Update ja.json
  UIInfoSuite2/i18n/ja.json
Labels: translation

#148 Update fr.json
  UIInfoSuite2/i18n/fr.json
Labels: translation
