Repository Annosz/UIInfoSuite2, pull requests merged in 2023-01, with the labels that each got.

#275 Find Robin's spritesheet correctly
  UIInfoSuite2/UIElements/ShowRobinBuildingStatusIcon.cs
Labels: bug

#276 Do not show the shipping bin icon for fish
  UIInfoSuite2/UIElements/ShowItemHoverInformation.cs
  docs/shipping_bin.md
Labels: bug

#284 Enable null checking and add UIInfoSuite2.csproj.local
  UIInfoSuite2/.gitignore
  UIInfoSuite2/UIInfoSuite2.csproj
Labels: code cleanup

#287 Update french translation
  UIInfoSuite2/i18n/fr.json
Labels: translation

#285 Refactor experience bar functionality
  UIInfoSuite2/Compatibility/ExperienceBar.cs
  UIInfoSuite2/UIElements/ExperienceBar.cs
  UIInfoSuite2/UIElements/ExperienceElements/DisplayedExperienceBar.cs
  UIInfoSuite2/UIElements/ExperienceElements/DisplayedExperienceValue.cs
  UIInfoSuite2/UIElements/ExperienceElements/DisplayedLevelUpMessage.cs
Labels: code cleanup
